export const FETCH_ALBUMS_PAGE = 'FETCH_ALBUMS_PAGE';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
export const FETCH_ALBUMS_FAIL = 'FETCH_ALBUMS_FAIL';

export const FETCH_PHOTOS_PAGE = 'FETCH_PHOTOS_PAGE';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAIL = 'FETCH_PHOTOS_FAIL';
